version: '3'
services:
  app:
    image: pedrohlucena/simple_product_api:latest
    build: .
    ports:
      - 3003:3003
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
